  
version: "3.7"
services:
  app:
    container_name: app
    build: ./app/
    volumes:
      - logs:/var/log/app/
    links:
      - filebeat
  
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.6.0
    volumes:
      - logs:/var/log/app/
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash

  logstash:
    container_name: logstash
    image: logstash:7.6.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
     

volumes:
  logs: 